export default {
	zydeco_bones_v1: {
		title: 'zydeco_poet_v1.2',
		css: 'zydeco1.1.css',
		html: 'zydeco1.1.htm',
		bg: 'zydeco1.1.png',
		bg_dim_x: '640',
		bg_dim_y: '480',
		bg_colors: [
			'red',
			'green',
			'#ff00ff',
			'#AF10EA',
			'#B2AA11',
			'#80FF80',
			'#8000FF',
			'#525C27',
			'#889D86',
			'gold',
			'DeepPink',
			'GreenYellow',
			'LightSeaGreen',
			'YellowGreen',
			'#19A3FF'
		],
		speech_parts: [
			'prio',
			'arts',
			'adje',
			'subs',
			'verb',
			'conc',
			'ends',
			'seco'
		],
		templates: [
			'prio arts adje subs verb ends verb comma seco adje subs conc verb ends period',
			'arts prio adje ends comma subs verb adje seco ends period adje verb comma prio subs',
			'prio subs adje verb ends comma seco arts adje subs conc verb ends period',
			'arts adje subs verb ends conc verb comma seco prio adje subs verb ends period'
		],
		notes: 'Doom scroll mode added.  Infinite scroll implementation with procedurally generated verses.',
		sources: ['original script by Sharkey', 'appendix of math book']
	},
	prio: [
		'Yes!',
		'Consider',
		'While',
		'With',
		'No!',
		'Behold',
		'Witness',
		'See',
		'Great is',
		'Wonderful is',
		'Take care:',
		'Ever',
		'Where can I find',
		'Look:',
		'I searched',
		'I found',
		'... And',
		'Within the crippled hand',
		'This is',
		'You are',
		'She has become',
		'We are not',
		'The device is',
		'They jumped',
		'These words become',
		'Our thoughts entangle',
		'Once upon a time, ',
		'Alas!',
		'Imagine',
		'Suppose',
		'Perhaps',
		'Indeed',
		'Observe',
		'Mark well:',
		'Listen',
		'How strange',
		'What if',
		'I remember',
		'I forget',
		'Tell me',
		'They say',
		'We know',
		'I wonder',
		'Beware:',
		'Suddenly',
		'Surely',
		'Never mind',
		'As it was',
		'Your voice became',
		'His fingers traced',
		'The darkness holds',
		'Beyond all measure',
		'Consider this:',
		'Recall when',
		'Think of',
		'Believe me',
		'Trust that',
		'Know that',
		'Understand',
		'Realize',
		'Admit',
		'Confess',
		'Reveal',
		'Conceal',
		'Discover',
		'Uncover',
		'Hide',
		'Find',
		'Seek',
		'Search',
		'Hunt',
		'Chase',
		'Pursue',
		'Abandon',
		'Release',
		'Clutch',
		'Grasp',
		'Hold',
		'Break',
		'Shatter',
		'Freeze',
		'Burn',
		'Drown',
		'Suffocate',
		'Wonder about',
		'Dream of',
		'Believe in',
		'Deny',
		'Accept',
		'Reject',
		'Embrace',
		'Resist',
		'Surrender',
		'Fight for',
		'Long for',
		'Yearn for',
		'Mourn',
		'Celebrate',
		'Despair',
		'Hope',
		'Fear',
		'Desire',
		'Hate',
		'Love',
		'Forgive',
		'Condemn',
		'Why?',
		'How so?',
		'When?',
		'Where?',
		'Who decides?',
		'How is it that',
		'What becomes',
		'Right now',
		'This moment',
		'As we speak',
		'Currently',
		'At this very instant',
		'You must',
		'You should',
		'Listen to me',
		'Hear this',
		'Pay attention',
		'I tell you',
		'Understand me'
	],
	arts: [
		'the',
		'one',
		'an ancient',
		'every',
		'no',
		'not the',
		'in the',
		'on the',
		'some of the',
		'that but not a',
		'then the',
		'in the way that a',
		'like the',
		'the one that the',
		'some of his',
		'the way that a',
		'outside our',
		'overcome by',
		'interspersed between their',
		'deep inside its',
		'and such as',
		'any of the',
		'all of the',
		'most of the',
		'few of the',
		'both the',
		'either the',
		'neither the',
		'such a',
		'many of the',
		'several of the',
		'other than the',
		'instead of the',
		'beyond the',
		'beneath the',
		'within their',
		'across the',
		'throughout their',
		'among the',
		'during the',
		'before the',
		'after the',
		'within the realm of',
		'beyond the scope of',
		'beside the',
		'beside their',
		'underneath the',
		'over the course of',
		'in spite of the',
		'despite the',
		'without the',
		'with all of the',
		'inside their',
		'inside the',
		'outside the',
		'around the',
		'through the',
		'past the',
		'against the',
		'above the',
		'below the',
		'toward the',
		'away from the',
		'apart from the',
		'along the',
		'alongside the',
		'between the',
		'amid the',
		'amidst the',
		'save for the',
		'except for the',
		'excluding the',
		'including the',
		'apart from all of the',
		'next to the',
		'near to the',
		'far from all of the',
		'close to the',
		'within sight of the',
		'out of the',
		'into the',
		'through which the',
		'by way of the',
		'in place of the',
		'the instructions for',
		'the manual of',
		'the steps to',
		'the method of'
	],
	adje: [
		'pert',
		'mottled',
		'Warholian',
		'blanched',
		'hounds-tooth',
		'burning',
		'marshmallowed',
		'beautiful',
		'naked',
		'peculiar',
		'glittery',
		'violent',
		'pointless',
		'gypsum',
		'heavy',
		'primordial',
		'lowercase',
		'prime',
		'tiny',
		'clairvoyant',
		'poor',
		'eccentric',
		'deep',
		'magical',
		'total',
		'green',
		'small',
		'loyal',
		'portable',
		'honest',
		'fearless',
		'opulent',
		'a native',
		'wet',
		'cold',
		'intense',
		'homeless',
		'placid',
		'calm',
		'cool',
		'blue',
		'mindful',
		'dull',
		'spiritual',
		'dark',
		'crashing',
		'razor',
		'cotton',
		'wooden',
		'tin',
		'copper',
		'empty',
		'lone',
		'enchanted',
		"midnight's",
		'morning',
		"night-time's",
		"nightingale's",
		'electric',
		'kind',
		'putative',
		'patient',
		'souls',
		'Moorish',
		'Venetian',
		'analogue',
		'solar',
		'impossible',
		'abortive',
		'gray',
		'milky',
		'slumbering',
		'deft',
		'dark',
		'unmoving',
		'paper',
		'Reykjavik',
		'drying',
		'forgotten',
		'leveling',
		'honorific',
		'yellow',
		'sarcastic',
		'pungent',
		'over-stuffed',
		'colloquial',
		'severed',
		'aromatic',
		'elastic',
		'angelic',
		'superfluous',
		'mioptic',
		'effervescent',
		'caustic',
		'harrowing',
		'quivering',
		'shivering',
		'bruised',
		'disregarded',
		'antecedent',
		'arbitrary',
		'antisymmetric',
		'asymmetric',
		'binary',
		'bound',
		'cardinal',
		'consequential',
		'conclusive',
		'congruent',
		'connective',
		'contradictory',
		'divided',
		'equinumerous',
		'existential',
		'exclusive',
		'equivalent',
		'exhausted',
		'exhaustive',
		'fixed',
		'finite',
		'geometric',
		'harmonic',
		'inclusive',
		'inductive',
		'inverse',
		'logarithmic',
		'exponential',
		'reflexive',
		'minimal',
		'proper',
		'real',
		'recursive',
		'refined',
		'vacuous',
		'upper',
		'lower',
		'inner',
		'outer',
		'subjective',
		'modular',
		'standard',
		'multidimensional',
		'default',
		'integrated',
		'shorthand',
		'characteristic',
		'unassigned',
		'undeclared',
		'infinite',
		'continuous',
		'numeric',
		'repetitive',
		'formal',
		'parameterized',
		'dynamic',
		'static',
		'iterative',
		'recursive',
		'nested',
		'equivalent',
		'octal',
		'floating-point',
		'tangential',
		'perpendicular',
		'standard',
		'nonstandard',
		'nullified',
		'enumerated',
		'constant',
		'automatic',
		'volatile',
		'macroscopic',
		'minute',
		'gargantuan',
		'allocated',
		'vindicated',
		'validated',
		'tensile',
		'enchanted',
		'morose',
		'pungent',
		'odorific',
		'multiplicitous',
		'teetering',
		'decadent',
		'humble',
		'bounded',
		'limitless',
		'hopeful',
		'brackish',
		'slackened',
		'spastic',
		'haptic',
		'elastic',
		'drastic',
		'plastic',
		'rasping',
		'ungraspable',
		'unattached',
		'reactive',
		'blasted',
		'tattered',
		'eratic',
		'medical',
		'medicinal',
		'pensive',
		'elliptic',
		'grimacing',
		'holstered',
		'molting',
		'roasted',
		'toasted',
		'molested',
		'tested',
		'festive',
		'erect',
		"bless'ed",
		'wedded',
		'festering',
		'fastidious',
		'collapsing',
		'usurping',
		'syrupy',
		'lurching',
		'hard-working',
		'perfect',
		'motorific',
		'haunted',
		'laundered',
		'pontific',
		'monstrous',
		'dolled-up',
		'choked-up',
		'moping',
		'rolling',
		'ogreish',
		'mopey',
		'alabaster',
		'plastered',
		'pacified',
		'bottom-feeding',
		'flashy',
		'fleshy',
		'pulsating',
		'dripping-wet',
		'excited',
		'tight',
		'sweet',
		'juicy',
		'ample',
		'bulbous',
		'plump',
		'tasty',
		'delicious',
		'juicy',
		'deep',
		'massive',
		'throbbing',
		'engorged',
		'heavy',
		'stinky',
		'buff',
		'symbiotic',
		'enlarged',
		'ribbed',
		'acceptable',
		'accidental',
		'recommended',
		'artificial',
		'armored',
		'audible',
		'tripping',
		'hot',
		'heated',
		'screwless',
		'diverse',
		'calculating',
		'cold',
		'dry',
		'electrical',
		'minimum',
		'essential',
		'interrogative',
		'skin',
		'equipment',
		'sunken',
		'residual',
		'alternative',
		'burning',
		'hazardous',
		'snap-in',
		'punch-out',
		'geometric',
		'isometric',
		'male',
		'female',
		'androgynous',
		'indigenous',
		'indigent',
		'reduced',
		'hermetic',
		'intermediate',
		'substitute',
		'neural',
		'nervous',
		'zig-zag',
		'high-leg',
		'red-leg',
		'wild-leg',
		'overloaded',
		'outdoor',
		'indoor',
		'emergency',
		'permanent',
		'dedicated',
		'advanced legal',
		'neutral',
		'airtight',
		'suspended',
		'fused',
		'metallic',
		'poke-through',
		'third-party',
		'after-market',
		'rooftop',
		'recommended',
		'refrigerated',
		'disconnected',
		'unprotected',
		'destructive',
		'emergent',
		'and such as',
		'peripheral',
		'ralphable',
		'bloody',
		'spunk',
		'ass',
		'choad',
		'pontifical',
		'jack-knifed',
		'EZ',
		'divine',
		'holy',
		'complicated',
		'tense',
		'beneficial',
		'crippled',
		'dented',
		'rented',
		'kumbaya',
		'one-eyed',
		'trouser',
		'seventeen',
		'ninety-nine',
		'one million',
		'three-fold',
		'ridiculous',
		'absurd',
		'laughable',
		'preposterous',
		'hilariously',
		'better',
		'worse',
		'stronger',
		'weaker',
		'faster',
		'slower',
		'higher',
		'lower'
	],
	subs: [
		'flower',
		'altar',
		'jet',
		'theater',
		'phonics',
		'delta',
		'Egyptian',
		'Phoenician',
		'faith foam',
		'soul',
		'polyglot',
		'Sumatran',
		'chorus',
		'teacher',
		'ocean',
		'keeper',
		'melon',
		'shell',
		'twig',
		'symbol',
		'order',
		'craftsman',
		'still life',
		'dragonfly',
		'flame',
		'fame',
		'wing',
		'circle',
		'drop',
		'doubt',
		'lover',
		'virgin',
		'monolith',
		'register',
		'lobby',
		'surface reflection',
		'nipple',
		'creep',
		'foam',
		'vapor',
		'fruit',
		'youth',
		'deer',
		'thought',
		'posture',
		'poet',
		'theologian',
		'mime',
		'preacher',
		'box',
		'idea',
		'word',
		'sound',
		'utterance',
		'mind',
		'song',
		'music box',
		'mouse',
		'glimmer',
		'speck',
		'pool',
		'snowfall',
		'heart',
		'soul',
		'vicar',
		'breast',
		'bosom',
		'firework',
		'firefly',
		'tales',
		'mask',
		'wave',
		'swell',
		'hand',
		'tide',
		'flesh',
		'moon',
		'star',
		'lighthouse',
		'bee',
		'egg',
		'searcher',
		'sleeper',
		'cigarette',
		'chimera',
		'shadow',
		'orca',
		'airship',
		'attitude',
		'tower',
		'body',
		'stalk',
		'sketch',
		'nothing',
		'somethings',
		'coin',
		'Earth',
		'chair',
		'inquisition',
		'banana',
		'math',
		'map',
		'liquid',
		'way',
		'number',
		'zero',
		'repeater',
		'dial',
		'sundry',
		'slumber',
		'peasant',
		'pocket-watch',
		'dirge',
		'raft',
		'bud',
		'sand',
		'salt',
		'midwife',
		'keyboard',
		'finger',
		'system',
		'space station',
		'bug',
		'spare bedroom',
		'hairspray',
		'Reykjavik',
		'pistol',
		'criminal',
		'venison',
		'pension',
		'penchant',
		'vitriol',
		'flippancy',
		'absorption',
		'bijection',
		'injection',
		'lemma',
		'induction',
		'modulo',
		'modus',
		'principles',
		'proof',
		'strategy',
		'perfection',
		'power',
		'paradox',
		'inference',
		'restriction',
		'remainder',
		'sequence',
		'dominance',
		'order',
		'surjection',
		'tautology',
		'trijection',
		'trichotomy',
		'truth',
		'theorem',
		'index',
		'variable',
		'diagram',
		'chart',
		'vertex',
		'universe of discourse',
		'prototype',
		'declaration',
		'expression',
		'strings',
		'break',
		'conversion',
		'ceiling',
		'floor',
		'backslash',
		'tangent',
		'streams',
		'comment',
		'directive',
		'input',
		'output',
		'label',
		'arrow',
		'pointer',
		'modulus',
		'series',
		'function',
		'statement',
		'ampersand',
		'umlaut',
		'validation',
		'moment',
		'particle',
		'rhombus',
		'fiber',
		'oatmeal',
		'rubber',
		'growth',
		'oats',
		'rope',
		'moat',
		'hopefulness',
		'vehicle',
		'creature',
		'detour',
		'features',
		'future',
		'wellspring',
		'jokes',
		'handbag',
		'temple',
		'bedding',
		'pillow',
		'books',
		'words',
		'grease',
		'pimples',
		'master',
		'bazooka',
		'cartoon',
		'piles',
		'driver',
		'niceness',
		'desert heat',
		'bees',
		'pupa',
		'knees',
		'blister',
		'sister',
		'twister',
		'tsunami',
		'puppet show',
		'rooster',
		'tulips',
		'music',
		'beauty',
		'future',
		'feature',
		'mandingo',
		'ring finger',
		'dead ringer',
		'harbinger',
		'artifice',
		'market',
		'carpet',
		'fish',
		'nautilus',
		'topics',
		'libido',
		'temptress',
		'vessel',
		'temptation',
		'arousal',
		'proposal',
		'proposition',
		'apostle',
		'acolyte',
		'devotee',
		'whore',
		'petri dish',
		'accolades',
		'prescription',
		'medicine',
		'remedy',
		'feldspar',
		'animal',
		'vegetable',
		'mineral',
		'octopus',
		'devil',
		'mermaid',
		'unicorn',
		'robot',
		'vampire',
		'transsexual',
		'root',
		'pole',
		'member',
		'flesh',
		'chimp',
		'chimpanzee',
		'monkey',
		'gorilla',
		'ape',
		'homosapien',
		'cave man',
		'proselyte',
		'priest',
		'dinner',
		'satellite',
		'witness',
		'god',
		'stooge',
		// 'prot�g�',
		'savant',
		'revolution',
		'convolution',
		'zealot',
		'pupil',
		'secretary',
		'underling',
		'parasite',
		'virus',
		'cohabitant',
		'sycophant',
		'minion',
		'client',
		'mother',
		'glim',
		'cheer-me-ups',
		'gift',
		'receptacle',
		'outlet',
		'approval',
		'ballast',
		'limitations',
		'nomograph',
		'feeder',
		'breeder',
		'guava',
		'plans',
		'diagrams',
		'terminal',
		'mechanism',
		'crawl space',
		'diversity',
		'capacity',
		'cartridge',
		'disc',
		'sphere',
		'shock',
		'supply',
		'demand',
		'heretic',
		'discharge',
		'service feeder',
		'exception',
		'protection',
		'entrance',
		'exit',
		'rape',
		'ducts',
		'plenum',
		'pipe',
		'nameplate',
		'badge',
		'checklist',
		'exemption',
		'location',
		'cross-section',
		'burial',
		'control',
		'example',
		'sump pump',
		'tubing',
		'revolver',
		'rod',
		'guzzler',
		'taint',
		'#@^&%',
		'dumpster',
		'magnet',
		'collapse',
		'habit',
		'habitat',
		'grabber',
		'octomom',
		'stripper',
		'tension',
		'wizard',
		'invention',
		'denizen',
		'quilt',
		'quilted-softness',
		'yogurt',
		'snake',
		'gopher',
		'lumber',
		'woodland creatures',
		'intelligence',
		'verb',
		'moniker',
		'pseudonym',
		'homophone',
		'phone',
		'cyberpolice',
		'instruction',
		'manual',
		'procedure',
		'protocol',
		'blueprint',
		'Mozart',
		'Newton',
		'Shakespeare',
		'Cairo',
		'Mars',
		'Amazon',
		'the Vatican',
		'Silicon Valley',
		'seven',
		'forty-two',
		'pi',
		'epsilon',
		'one million'
	],
	verb: [
		'life masking',
		'creep',
		'drifting',
		'jetting',
		'echoing',
		'waxing',
		'dreaming',
		'kissing',
		'fertilizing',
		'fluttering',
		'dithering',
		'tickling',
		'spiraling',
		'skidding',
		'swirling',
		'looking in',
		'brewing',
		'drawing',
		'casting',
		'tickling',
		'docking',
		'beating',
		'surpassing',
		'achieved',
		'approached',
		'fighting',
		'dancing',
		'growing',
		'visiting',
		'seeing',
		'steering',
		'crawling',
		'dying',
		'yielding',
		'dredged',
		'traveling',
		'etching',
		'spilling',
		'whispering',
		'swimming',
		'drinking',
		'gulping',
		'clasping',
		'drooping',
		'thinning',
		'digging',
		'beating',
		'glowing',
		'bursting',
		'crunching',
		'releasing',
		'hovering',
		'sinking',
		'sulking',
		'heralded',
		'quivers',
		'shivers',
		'lies awake',
		'sings',
		'thrashes',
		'melts',
		'sewed',
		'milks',
		'repeats',
		'folds',
		'pours',
		'drips',
		'tears',
		'wanders',
		'winds',
		'chants',
		'clicked',
		'brushed',
		'pulping',
		'recovering',
		'gesticulating',
		'oozing',
		'seething',
		'tiptoeing',
		'recovering',
		'roasting',
		'hoping',
		'floating',
		'jumping',
		'running',
		'skipping',
		'disregarding',
		'knocking',
		'cropping',
		'socking',
		'rowing',
		'knowing',
		'exploding',
		'goading',
		'hoisting',
		'masking',
		'creeps',
		'drifts',
		'jets',
		'echoes',
		'waxed',
		'dreamed',
		'kissed',
		'fertilized',
		'fluttered',
		'dithers',
		'tickles',
		'spirals',
		'skidded',
		'swirled',
		'viewed',
		'brews',
		'drew',
		'casts',
		'tickled',
		'docked',
		'beats',
		'surpassed',
		'will achieve',
		'approaches',
		'fights',
		'dances',
		'grows',
		'visits',
		'sees',
		'steers',
		'crawled',
		'dies',
		'yields',
		'dredges',
		'travels',
		'etches',
		'spills',
		'whispers',
		'swims',
		'drinks',
		'gulps',
		'clasps',
		'droops',
		'thins',
		'digs',
		'beat',
		'glows',
		'bursts',
		'crunches',
		'releases',
		'hovers',
		'sinks',
		'sulked',
		'lying awake',
		'singing',
		'thrashing',
		'melting',
		'sewing',
		'milking',
		'repeating',
		'folding',
		'pouring',
		'dripping',
		'tearing',
		'wandering',
		'winding',
		'chanting',
		'clicking',
		'brushing',
		'pushed',
		'recovers',
		'gesticulates',
		'gesticulate',
		'oozes',
		'seethes',
		'tiptoes',
		'will roast',
		'hopes',
		'floats',
		'jumps',
		'ran',
		'skipped',
		'knocked',
		'cropped',
		'socks',
		'rows',
		'knows',
		'explodes',
		'goads',
		'boils',
		'bubbles',
		'backtracing',
		'jostle',
		'rocking',
		'rolling',
		'dwell',
		'impede',
		'skim',
		'utilize',
		'tapped',
		'guzzle',
		'gulping',
		'gulps',
		'gulp',
		'slurp',
		'strutting that',
		'explaining',
		'instructing',
		'detailing',
		'specifying',
		'documenting',
		'counting',
		'measuring',
		'quantifying',
		'multiplying',
		'dividing',
		'reasoning',
		'concluding',
		'inferring',
		'deducing',
		'proving',
		'is happening',
		'occurring',
		'unfolding',
		'transpiring',
		'taking place',
		'happening now',
		'denying',
		'rejecting',
		'refusing',
		'negating',
		'contradicting',
		'exceeding',
		'surpassing',
		'comparing',
		'contrasting',
		'matching',
		'opposing',
		'addressing you',
		'speaking to you',
		'commanding',
		'beseeching',
		'imploring',
		'demanding'
	],
	conc: [
		'must be',
		'realizes there should be something',
		'is',
		'should be',
		'is never',
		'cannot be',
		'listlessly',
		'remarkably',
		'regrettably',
		'often does',
		'was',
		'became tempted by',
		'was forced to',
		'could not help but',
		'unfortunately',
		'fortunately',
		'is often',
		'flies in the face of',
		'defies the logic of',
		'as foretold in the prophecy',
		'shall be',
		'might be',
		'could be',
		'would be',
		'appears to be',
		'seems to be',
		'becomes',
		'remains',
		'grows to be',
		'turns out to be',
		'sadly',
		'inexplicably',
		'mysteriously',
		'undeniably',
		'inevitably',
		'contradicts all reason',
		'embraces the darkness',
		'surrenders to the void',
		'whispers what cannot be spoken',
		'embodies the unreachable',
		'dwells in silence',
		'persists against hope',
		'crumbles under scrutiny',
		'transcends understanding',
		'dissolves into memory',
		'lingers in the margins',
		'resonates with longing',
		'pulses with hidden meaning',
		'obscured by time',
		'revealed in fragments',
		'haunted by its own nature',
		'confined within paradox',
		'dances at the edge',
		'spirals endlessly',
		'mirrors what cannot be seen',
		'speaks in riddles',
		'conceals more than it shows',
		'glimmers like starlight',
		'echoes across centuries',
		'breaks all natural law',
		'drowns in its own contradiction',
		'blooms where nothing grows',
		'rises from ashes',
		'falls toward infinity',
		'stands witness to all things',
		'trembles with recognition',
		'shimmers between being and non-being',
		'holds fast to mystery',
		'aches with desire',
		'absorbs the light',
		'reflects the unreflective',
		'contains multitudes',
		'births itself anew',
		'answers only to silence',
		'bends the rules of grammar',
		'orchestrates the invisible',
		'mourns what never was',
		'celebrates what must not be',
		'stretches toward the void',
		'asks itself',
		'questions whether',
		'wonders if',
		'demands to know',
		'logically follows',
		'necessarily means',
		'implies',
		'entails',
		'proves',
		'ironically',
		'in all seriousness',
		'supposedly',
		'allegedly',
		'wink wink',
		'is occurring',
		'is happening',
		'unfolds',
		'happens',
		'takes place',
		'simply is not',
		'definitely is not',
		'in no way',
		'categorically not',
		'absolutely not',
		'never will be',
		'greater than',
		'less than',
		'superior to',
		'inferior to',
		'equivalent to',
		'opposite of'
	],
	ends: [
		'above',
		'over water',
		'apart',
		'like bugs',
		'like plants',
		'over',
		'on tape',
		'but I digress',
		'in unison',
		'in your eardrum',
		'as in dreams',
		'upwards',
		'and more',
		'because',
		'beyond',
		'about',
		'pass sundown',
		'to the sinner land',
		'slowly',
		'with pleasure',
		'from a computer crash',
		'in lust',
		'in degrees',
		'in various forms',
		'etc.',
		'to be continued',
		'from the future',
		'down down down',
		'double',
		'(as needed)',
		'(in silence)',
		'(always on the tip)',
		'on the hill',
		'on the asphalt with bright chalk',
		'on the chalkboard with white chalk',
		"packed in some kid's lunch",
		'of bare chests',
		'giver',
		'perfume',
		'alone',
		'on beams',
		'forever',
		'and so on',
		'and on and on',
		'in twilight',
		'on drums',
		'at home',
		'the lake',
		'upstream',
		'over your shoulder',
		'(like in heaven)',
		'beneath fresh wounds',
		'down rabbit holes',
		'in storm-glass',
		'under the deep wood',
		'during the bedtime',
		'like a boy',
		'twice',
		'at dusk',
		'not ever',
		'at noon',
		'for tomorrow',
		'on film',
		'with deep swelling',
		'intricacies',
		'in inaccuracies',
		'Rittenhouse Squares',
		'in knots',
		'in dead space',
		'in daylight',
		'like the frog',
		'to shadow land',
		'my daydream',
		'on windows',
		'for',
		'up pipe-dreams',
		'unquestioning',
		'as ever',
		'darkness',
		'my memory',
		'diaphanously',
		'(okay; fine)',
		'only',
		'against',
		'against flesh',
		'cannot be',
		'to the Pleiades',
		'posthumously',
		'past nighttime',
		'in twilight',
		'into heaven',
		'(almost to heaven)',
		'up from hell',
		'in absence',
		'- tragic',
		'in Paris',
		'in Copenhagen',
		'in Tokyo',
		'in the Osaka Night',
		'in the anthill',
		'going up like bees',
		'and so on',
		'in dire need',
		'outside the typical',
		'and we can only guess what it means',
		'or something similar',
		'from under the stairs',
		'for lack of a better quo status',
		'and balked in terror',
		'and ran off never to be seen again.',
		'for the better',
		'in spite of predictions',
		'on lubricated plastics',
		'under the radar',
		'because it was best',
		'meticulously',
		'to be arbitrary',
		'in astoundment',
		'as much as ever',
		'beside still waters',
		'therefore',
		'thus',
		'consequently',
		'as a result',
		'because of this',
		'which explains'
	],
	seco: [
		'no',
		'not one',
		'that',
		'not that',
		'far from the',
		'near the',
		'not the',
		'the',
		'the solitary',
		'a neat',
		'the more',
		'until the',
		'the same',
		'perhaps the',
		'alas the',
		'kind of like a',
		'...',
		'more known that the',
		'ad nauseam the',
		'virtually the',
		'practically the',
		'scarcely the',
		'barely the',
		'hardly the',
		'almost the',
		'nearly the',
		'supposedly the',
		'allegedly the',
		'rumored to be the',
		'the only',
		'a certain',
		'another',
		'each of the',
		'every single',
		'what remains of the',
		'the last of the',
		'the first of the',
		'still the',
		'once the',
		'and such as',
		'your own',
		'your choice',
		'your fault',
		'your shame',
		'your burden',
		'your truth'
	]
};
